openapi: 3.0.0

info:
    title: ONB Express Auth Server
    description: |
      Данный сервис предоставляет возможность получения Access Token для авторизации и Refresh Token для получения новой пары без аутентификации. 

      Пример ответа с токенами при успешной аутентификации:

        ```json
        {
        "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDdmMTkxZTgxMGMxOTcyOWRlODYwZWEiLCJncm91cCI6ImN1c3RvbWVyIiwiZXhwaXJlcyI6MTY4NjUxMDgxNH0.-pxtW7AEraTNnxkgf-_t0ygCfslMcMHlUSdZhlZKDvk",
        "refresh_token": "IwOGYzYTlmM2YxOTQ5MGE3YmNmMDFkNTVk",
        "token_type": "Bearer",
        "expires_in": 3600,
        "scope": "order user address"
        }
        ```
      
      Для авторизации последующих запросов к непубличным эндпоинтам следует передавать полученный Access Token в заголовке Authorization в формате Bearer:
      ```
      Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDdmMTkxZTgxMGMxOTcyOWRlODYwZWEiLCJncm91cCI6ImN1c3RvbWVyIiwiZXhwaXJlcyI6MTY4NjUxMDgxNH0.-pxtW7AEraTNnxkgf-_t0ygCfslMcMHlUSdZhlZKDvk
      ```
      В целях безопасности Access Token имеет короткое время жизни, около 5-10 минут (точное время жизни указано в значении *expires_in*). 
      После истечения срока жизни закрытые сервисы будут отвечать кодом 401 с сообщением что токен доступа истек. Для получения нового токена следует использовать Refresh Token.

      На данный момент поддерживается 3 способа получения токена:
        - [С отправкой одноразового пароля (OTP) через СМС (для мобильного приложения)](#post-/token/otp)
        - [С использованием идентификатора приложения и секретного ключа (для 1С)](#post-/token/client)
        - [С использованием ранее полученного refresh token](#post-/token/refresh)

      

    version: 0.1.0
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
    - url: https://auth.onbexpress.ru
      description: Production Server
    - url: https://mock.onbexpress.ru/auth
      description: Mock Server
    
tags: 
    - name: Получение токена
      description: Эндпоинты для получения токена

paths:
    /phone/otp:
      $ref: routes/phone.otp.yaml
    /certs:
      $ref: routes/certs.yaml
    /token/otp:
      $ref: routes/token.otp.yaml
    /token/client:
      $ref: routes/token.client.yaml
    /token/refresh:
      $ref: routes/token.refresh.yaml
    


components:
    schemas:
        $ref: './schemas/_index.yaml'
    responses: 
        $ref: './responses/_index.yaml'